function [calc_value, data_save] = structure_ECM_0D(options)

% Initilization ###########################################################
calc_value=struct(...
    'time',zeros(2,6) ...
        ,'U',zeros(2,6) ...
        ,'T',zeros(2,6) ... % For 6 different Si contents
        ,'SoC',zeros(2,6) ...
        ,'OCV',zeros(2,6) ...
        ,'h',zeros(2,6) ...
        ,'Q',zeros(1,6) ...
        ,'Entropy',zeros(2,6) ...
        ,'Q_irr',zeros(1,6) ...
        ,'Q_rev',zeros(1,6) ...
        ,'Q_cooling',zeros(1,6) ...
      ,'Aging',struct(... 
         'SoH_C',zeros(1,6) ...
        ,'SoH_R',zeros(1,6) ...
        )...
     );
% Structure to Save Data ##################################################
data_save.time=zeros(1,6);
% All of this is just initializing all the saved information to zero so
% that the program allocates approperate amount of space.

% Cell, currently this is the only data being saved.
for trans=1:length(options.Save.Cell(:,1))
    data_save.(options.Save.Cell{trans,:})=zeros(1,6);
end
end

