function [calc_value, data_save] = structure_ECM_2RC_VolThev(options)

% Initilization ###########################################################
calc_value=struct(...
    'time',zeros(2,1) ...
        ,'P',zeros(2,1) ...
        ,'P_control',zeros(2,1) ...
        ,'I_tot',zeros(2,1) ...
        ,'j_Si',zeros(2,1) ...
        ,'j_Gr',zeros(2,1) ...
        ,'I_Si',zeros(2,1) ...
        ,'I_Gr',zeros(2,1) ...
        ,'U',zeros(2,1) ...
        ,'SoC',zeros(2,1) ...
        ,'OCV',zeros(2,1) ...
        ,'h',zeros(2,1) ...
        ,'Q',zeros(1,1) ...
        ,'Entropy',zeros(2,1) ...
        ,'Q_irr',zeros(1,1) ...
        ,'Q_rev',zeros(1,1) ...
        ,'Q_cooling',zeros(1,1) ...
    ,'T',struct ( ...
        'T_lowC',zeros(1,1)...
        ,'T_midC',zeros(1,1)...
        ,'T_highC',zeros(1,1)...
        )...
    ,'ECM',struct(...
        'R',zeros(2,1) ...
        ,'R_RC1',zeros(2,1) ...
        ,'tau_RC1',zeros(2,1) ...
        ,'R_RC2',zeros(2,1) ...
        ,'tau_RC2',zeros(2,1) ...
        ,'Usc',zeros(2,1) ...
        ,'U_R',zeros(2,1) ...
        ,'U_RC1',zeros(2,1) ...
        ,'U_RC2',zeros(2,1) ...
        )...
      ,'Aging',struct(... 
         'SoH_C',zeros(1,1) ...
        ,'SoH_R',zeros(1,1) ...
        )...
    );
% Structure to Save Data ##################################################
data_save.time=zeros(1,1);
% All of this is just initializing all the saved information to zero so
% that the program allocates approperate amount of space.
%Cell
for trans=1:length(options.Save.Cell(:,1))
    data_save.(options.Save.Cell{trans,:})=zeros(1,1);
end

%% Initialize Current Distribution Arrays (PRAVEEN)
% Dimensions: (time_steps, Si_wt%, C_rates)

n_wtSi  = length(options.wtSi);
n_cRate = length(options.cRates);

data_save.current_dist.I_Si    = zeros(n_wtSi, n_cRate);
data_save.current_dist.I_G     = zeros(n_wtSi, n_cRate);
data_save.current_dist.j_Si    = zeros(n_wtSi, n_cRate);
data_save.current_dist.j_G     = zeros(n_wtSi, n_cRate);
data_save.current_dist.frac_Si = zeros(n_wtSi, n_cRate);
data_save.current_dist.frac_G  = zeros(n_wtSi, n_cRate);

%% ── Volumetric Capacity────────────────────────────────────────
% Dimensions: (n_wtSi x 1) — computed once per wt%, C-rate independent
data_save.vol_cap.wtSi = zeros(n_wtSi, 1);
data_save.vol_cap.G_A  = zeros(n_wtSi, 1);
data_save.vol_cap.P_A  = zeros(n_wtSi, 1);

% Case 1: Zero expansion
data_save.vol_cap.case1.V_A          = zeros(n_wtSi, 1);
data_save.vol_cap.case1.P_A_required = zeros(n_wtSi, 1);
data_save.vol_cap.case1.P_ALi        = zeros(n_wtSi, 1);
data_save.vol_cap.case1.E            = zeros(n_wtSi, 1);

% Case 2: Constant porosity — V_A_array has 5 porosity levels
data_save.vol_cap.case2.V_A          = zeros(n_wtSi, 1);
data_save.vol_cap.case2.V_A_array    = zeros(n_wtSi, 5);
data_save.vol_cap.case2.P_ALi        = zeros(n_wtSi, 1);
data_save.vol_cap.case2.E            = zeros(n_wtSi, 1);

% Case 3: Variable porosity
data_save.vol_cap.case3.V_A          = zeros(n_wtSi, 1);
data_save.vol_cap.case3.P_ALi        = zeros(n_wtSi, 1);
data_save.vol_cap.case3.E            = zeros(n_wtSi, 1);
end

