function [calc_value, data_save] = structure_ECM_2RC_VolThev(options)

% Initilization ###########################################################
calc_value=struct(...
    'time',zeros(2,1) ...
        ,'P',zeros(2,1) ...
        ,'P_control',zeros(2,1) ...
        ,'I',zeros(2,1) ...
        ,'U',zeros(2,1) ...
        ,'SoC', zeros(2,1) ...
        ,'OCV', zeros(2,1) ...
        ,'VV0', zeros(2,1) ...
        ,'dV_Si', zeros(2,1) ...
        ,'dV_Gr', zeros(2,1) ...
    ,'T',struct ( ...
        'T_lowC',zeros(1,1)...
        ,'T_midC',zeros(1,1)...
        ,'T_highC',zeros(1,1)...
        )...
    ,'ECM',struct(...
        'R',zeros(2,1) ...
        ,'R_RC1',zeros(2,1) ...
        ,'tau_RC1',zeros(2,1) ...
        ,'R_RC2',zeros(2,1) ...
        ,'tau_RC2',zeros(2,1) ...
        ,'Usc',zeros(2,1) ...
        ,'U_R',zeros(2,1) ...
        ,'U_RC1',zeros(2,1) ...
        ,'U_RC2',zeros(2,1) ...
        )...
    );
% Structure to Save Data ##################################################
data_save.time=zeros(1,1);
% All of this is just initializing all the saved information to zero so
% that the program allocates approperate amount of space.
%Cell
for trans=1:length(options.Save.Cell(:,1))
    data_save.(options.Save.Cell{trans,:})=zeros(1,1);
end
for trans=1:length(options.Save.ECM(:,1))
    data_save.ECM.(options.Save.ECM{trans,:})=zeros(1,1);
end
%% Initialize Current Distribution Arrays (PRAVEEN)
% Dimensions: (time_steps, Si_wt%, C_rates)
data_save.current_dist.I_Si = [];
data_save.current_dist.I_G = [];
data_save.current_dist.j_Si = [];
data_save.current_dist.j_G = [];
data_save.current_dist.eta = [];
data_save.current_dist.SOC = [];
data_save.current_dist.frac_Si = [];
data_save.current_dist.frac_G = [];

%ECM
% for trans=1:length(options.Save.ECM(:,1))
%     data_save.ECM.(options.Save.ECM{trans,:})(1,:)=zeros(1,1);
% end
% %Particle
% for trans=1:length(options.Save.Particle(:,1))
%     data_save.Particle.(options.Save.Particle{trans,:})=zeros(1,options.seg_particle);
% end
end

