function [battery_res,msg] = ECM_Parameter_ECM_0D(battery_res,param,options,msg)
%ECM_PARAMETER_ECM_0D Summary of this function goes here
%   Detailed explanation goes here
if options.bool.ini==1                                                     %Initialization
    tempValue=1;
else
    tempValue=2;
end
if options.bool.EIS==0 %Parametrization based on Pulse Data ###############
    if battery_res.P(tempValue,1)<0
        %R0 #######################################################################
        battery_res.ECM.R(tempValue,1)=param.fit.DCH.R0(battery_res.SoC(tempValue,1),battery_res.T(tempValue,1)) ...
            *battery_res.Aging.SoH_R(1,1)*options.Electrical.R_fac;
        if battery_res.ECM.R(tempValue,1)<0 ...
                || battery_res.ECM.R(tempValue,1)==0 ...
                || isnan(battery_res.ECM.R(tempValue,1))>0
            msg.error.ECM.R=1;
            battery_res.ECM.R(tempValue,1)=battery_res.ECM.R(tempValue,1).*floor(battery_res.ECM.R(tempValue,1)./abs(battery_res.ECM.R(tempValue,1)*1.05)) ...
                +floor(1-battery_res.ECM.R(tempValue,1)./abs(battery_res.ECM.R(tempValue,1)*1.05))*1e-3;
        end
        
        %RC1 ######################################################################
        battery_res.ECM.R_RC1(tempValue,1)=param.fit.DCH.R_RC1(battery_res.SoC(tempValue,1),battery_res.T(tempValue,1)) ...
            *battery_res.Aging.SoH_R(1,1)*options.Electrical.RC1_fac;
        if battery_res.ECM.R_RC1(tempValue,1)<0 ...
                || battery_res.ECM.R_RC1(tempValue,1)==0 ...
                || isnan(battery_res.ECM.R_RC1(tempValue,1))>0
            msg.error.ECM.R_RC1=1;
            battery_res.ECM.R_RC1(tempValue,1)=battery_res.ECM.R_RC1(tempValue,1).*floor(battery_res.ECM.R_RC1(tempValue,1)./abs(battery_res.ECM.R_RC1(tempValue,1)*1.05)) ...
                +floor(1-battery_res.ECM.R_RC1(tempValue,1)./abs(battery_res.ECM.R_RC1(tempValue,1)*1.05))*1e-3;
        end
        battery_res.ECM.tau_RC1(tempValue,1)=param.fit.DCH.tau_RC1(battery_res.SoC(tempValue,1),battery_res.T(tempValue,1)) ...
            *options.Electrical.tau_RC1_fac;
        if battery_res.ECM.tau_RC1(tempValue,1)<0 ...
                || battery_res.ECM.tau_RC1(tempValue,1)==0 ...
                || isnan(battery_res.ECM.tau_RC1(tempValue,1))>0
            msg.error.ECM.tau_RC1=1;
            battery_res.ECM.tau_RC1(tempValue,1)=battery_res.ECM.tau_RC1(tempValue,1).*floor(battery_res.ECM.tau_RC1(tempValue,1)./abs(battery_res.ECM.tau_RC1(tempValue,1)*1.05)) ...
                +floor(1-battery_res.ECM.tau_RC1(tempValue,1)./abs(battery_res.ECM.tau_RC1(tempValue,1)*1.05))*1e-3;
        end
        
        %RC2 ######################################################################
        battery_res.ECM.R_RC2(tempValue,1)=param.fit.DCH.R_RC2(battery_res.SoC(tempValue,1),battery_res.T(tempValue,1)) ...
            *battery_res.Aging.SoH_R(1,1)*options.Electrical.RC2_fac;
        if battery_res.ECM.R_RC2(tempValue,1)<0 ...
                || battery_res.ECM.R_RC2(tempValue,1)==0 ...
                || isnan(battery_res.ECM.R_RC2(tempValue,1))>0
            msg.error.ECM.R_RC2=1;
            battery_res.ECM.R_RC2(tempValue,1)=battery_res.ECM.R_RC2(tempValue,1).*floor(battery_res.ECM.R_RC2(tempValue,1)./abs(battery_res.ECM.R_RC2(tempValue,1)*1.05)) ...
                +floor(1-battery_res.ECM.R_RC2(tempValue,1)./abs(battery_res.ECM.R_RC2(tempValue,1)*1.05))*1e-3;
        end
        battery_res.ECM.tau_RC2(tempValue,1)=param.fit.DCH.tau_RC2(battery_res.SoC(tempValue,1),battery_res.T(tempValue,1)) ...
            *options.Electrical.tau_RC2_fac;
        if battery_res.ECM.tau_RC2(tempValue,1)<0 ...
                || battery_res.ECM.tau_RC2(tempValue,1)==0 ...
                || isnan(battery_res.ECM.tau_RC2(tempValue,1))>0
            msg.error.ECM.tau_RC2=1;
            battery_res.ECM.tau_RC2(tempValue,1)=battery_res.ECM.tau_RC2(tempValue,1).*floor(battery_res.ECM.tau_RC2(tempValue,1)./abs(battery_res.ECM.tau_RC2(tempValue,1)*1.05)) ...
                +floor(1-battery_res.ECM.tau_RC2(tempValue,1)./abs(battery_res.ECM.tau_RC2(tempValue,1)*1.05))*1e-3;
        end
        
        %RC3 ######################################################################
        battery_res.ECM.R_RC3(tempValue,1)=param.fit.DCH.R_RC3(battery_res.SoC(tempValue,1),battery_res.T(tempValue,1)) ...
            *battery_res.Aging.SoH_R(1,1)*options.Electrical.RC3_fac;
        if battery_res.ECM.R_RC3(tempValue,1)<0 ...
                || battery_res.ECM.R_RC3(tempValue,1)==0 ...
                || isnan(battery_res.ECM.R_RC3(tempValue,1))>0
            msg.error.ECM.R_RC3=1;
            battery_res.ECM.R_RC3(tempValue,1)=battery_res.ECM.R_RC3(tempValue,1).*floor(battery_res.ECM.R_RC3(tempValue,1)./abs(battery_res.ECM.R_RC3(tempValue,1)*1.05)) ...
                +floor(1-battery_res.ECM.R_RC3(tempValue,1)./abs(battery_res.ECM.R_RC3(tempValue,1)*1.05))*1e-3;
        end
        battery_res.ECM.tau_RC3(tempValue,1)=param.fit.DCH.tau_RC3(battery_res.SoC(tempValue,1),battery_res.T(tempValue,1)) ...
            *options.Electrical.tau_RC3_fac;
        if battery_res.ECM.tau_RC3(tempValue,1)<0 ...
                || battery_res.ECM.tau_RC3(tempValue,1)==0 ...
                || isnan(battery_res.ECM.tau_RC3(tempValue,1))>0
            msg.error.ECM.tau_RC3=1;
            battery_res.ECM.tau_RC3(tempValue,1)=battery_res.ECM.tau_RC3(tempValue,1).*floor(battery_res.ECM.tau_RC3(tempValue,1)./abs(battery_res.ECM.tau_RC3(tempValue,1)*1.05)) ...
                +floor(1-battery_res.ECM.tau_RC3(tempValue,1)./abs(battery_res.ECM.tau_RC3(tempValue,1)*1.05))*1e-3;
        end
    else
        %R0 #######################################################################
        battery_res.ECM.R(tempValue,1)=param.fit.CH.R0(battery_res.SoC(tempValue,1),battery_res.T(tempValue,1)) ...
            *battery_res.Aging.SoH_R(1,1)*options.Electrical.R_fac;
        if battery_res.ECM.R(tempValue,1)<0 ...
                || battery_res.ECM.R(tempValue,1)==0 ...
                || isnan(battery_res.ECM.R(tempValue,1))>0
            msg.error.ECM.R=1;
            battery_res.ECM.R(tempValue,1)=battery_res.ECM.R(tempValue,1).*floor(battery_res.ECM.R(tempValue,1)./abs(battery_res.ECM.R(tempValue,1)*1.05)) ...
                +floor(1-battery_res.ECM.R(tempValue,1)./abs(battery_res.ECM.R(tempValue,1)*1.05))*1e-3;
        end
        
        %RC1 ######################################################################
        battery_res.ECM.R_RC1(tempValue,1)=param.fit.CH.R_RC1(battery_res.SoC(tempValue,1),battery_res.T(tempValue,1)) ...
            *battery_res.Aging.SoH_R(1,1)*options.Electrical.RC1_fac;
        if battery_res.ECM.R_RC1(tempValue,1)<0 ...
                || battery_res.ECM.R_RC1(tempValue,1)==0 ...
                || isnan(battery_res.ECM.R_RC1(tempValue,1))>0
            msg.error.ECM.R_RC1=1;
            battery_res.ECM.R_RC1(tempValue,1)=battery_res.ECM.R_RC1(tempValue,1).*floor(battery_res.ECM.R_RC1(tempValue,1)./abs(battery_res.ECM.R_RC1(tempValue,1)*1.05)) ...
                +floor(1-battery_res.ECM.R_RC1(tempValue,1)./abs(battery_res.ECM.R_RC1(tempValue,1)*1.05))*1e-3;
        end
        battery_res.ECM.tau_RC1(tempValue,1)=param.fit.CH.tau_RC1(battery_res.SoC(tempValue,1),battery_res.T(tempValue,1)) ...
            *options.Electrical.tau_RC1_fac;
        if battery_res.ECM.tau_RC1(tempValue,1)<0 ...
                || battery_res.ECM.tau_RC1(tempValue,1)==0 ...
                || isnan(battery_res.ECM.tau_RC1(tempValue,1))>0
            msg.error.ECM.tau_RC1=1;
            battery_res.ECM.tau_RC1(tempValue,1)=battery_res.ECM.tau_RC1(tempValue,1).*floor(battery_res.ECM.tau_RC1(tempValue,1)./abs(battery_res.ECM.tau_RC1(tempValue,1)*1.05)) ...
                +floor(1-battery_res.ECM.tau_RC1(tempValue,1)./abs(battery_res.ECM.tau_RC1(tempValue,1)*1.05))*1e-3;
        end
        
        %RC2 ######################################################################
        battery_res.ECM.R_RC2(tempValue,1)=param.fit.CH.R_RC2(battery_res.SoC(tempValue,1),battery_res.T(tempValue,1)) ...
            *battery_res.Aging.SoH_R(1,1)*options.Electrical.RC2_fac;
        if battery_res.ECM.R_RC2(tempValue,1)<0 ...
                || battery_res.ECM.R_RC2(tempValue,1)==0 ...
                || isnan(battery_res.ECM.R_RC2(tempValue,1))>0
            msg.error.ECM.R_RC2=1;
            battery_res.ECM.R_RC2(tempValue,1)=battery_res.ECM.R_RC2(tempValue,1).*floor(battery_res.ECM.R_RC2(tempValue,1)./abs(battery_res.ECM.R_RC2(tempValue,1)*1.05)) ...
                +floor(1-battery_res.ECM.R_RC2(tempValue,1)./abs(battery_res.ECM.R_RC2(tempValue,1)*1.05))*1e-3;
        end
        battery_res.ECM.tau_RC2(tempValue,1)=param.fit.CH.tau_RC2(battery_res.SoC(tempValue,1),battery_res.T(tempValue,1)) ...
            *options.Electrical.tau_RC2_fac;
        if battery_res.ECM.tau_RC2(tempValue,1)<0 ...
                || battery_res.ECM.tau_RC2(tempValue,1)==0 ...
                || isnan(battery_res.ECM.tau_RC2(tempValue,1))>0
            msg.error.ECM.tau_RC2=1;
            battery_res.ECM.tau_RC2(tempValue,1)=battery_res.ECM.tau_RC2(tempValue,1).*floor(battery_res.ECM.tau_RC2(tempValue,1)./abs(battery_res.ECM.tau_RC2(tempValue,1)*1.05)) ...
                +floor(1-battery_res.ECM.tau_RC2(tempValue,1)./abs(battery_res.ECM.tau_RC2(tempValue,1)*1.05))*1e-3;
        end
        
        %RC3 ######################################################################
        battery_res.ECM.R_RC3(tempValue,1)=param.fit.CH.R_RC3(battery_res.SoC(tempValue,1),battery_res.T(tempValue,1)) ...
            *battery_res.Aging.SoH_R(1,1)*options.Electrical.RC3_fac;
        if battery_res.ECM.R_RC3(tempValue,1)<0 ...
                || battery_res.ECM.R_RC3(tempValue,1)==0 ...
                || isnan(battery_res.ECM.R_RC3(tempValue,1))>0
            msg.error.ECM.R_RC3=1;
            battery_res.ECM.R_RC3(tempValue,1)=battery_res.ECM.R_RC3(tempValue,1).*floor(battery_res.ECM.R_RC3(tempValue,1)./abs(battery_res.ECM.R_RC3(tempValue,1)*1.05)) ...
                +floor(1-battery_res.ECM.R_RC3(tempValue,1)./abs(battery_res.ECM.R_RC3(tempValue,1)*1.05))*1e-3;
        end
        battery_res.ECM.tau_RC3(tempValue,1)=param.fit.CH.tau_RC3(battery_res.SoC(tempValue,1),battery_res.T(tempValue,1)) ...
            *options.Electrical.tau_RC3_fac;
        if battery_res.ECM.tau_RC3(tempValue,1)<0 ...
                || battery_res.ECM.tau_RC3(tempValue,1)==0 ...
                || isnan(battery_res.ECM.tau_RC3(tempValue,1))>0
            msg.error.ECM.tau_RC3=1;
            battery_res.ECM.tau_RC3(tempValue,1)=battery_res.ECM.tau_RC3(tempValue,1).*floor(battery_res.ECM.tau_RC3(tempValue,1)./abs(battery_res.ECM.tau_RC3(tempValue,1)*1.05)) ...
                +floor(1-battery_res.ECM.tau_RC3(tempValue,1)./abs(battery_res.ECM.tau_RC3(tempValue,1)*1.05))*1e-3;
        end
    end
else %Parametrization based on EIS Data ###################################
    %EIS Data only for 25 °C right now
    %Zarc 1 & 2
    for ii=1:2
        for iii=1:length(options.Names_ECM(:,1))
            battery_res.ECM.(options.Names_Elements{ii,:}).(options.Names_ECM{iii,:})(tempValue,1)= ...
                interp1(param.fit.ECM.SoC,param.fit.ECM.(options.Names_Elements{ii,:}).(options.Names_ECM{iii,:}),battery_res.Cell.SoC(tempValue,1));
            if battery_res.ECM.(options.Names_Elements{ii,:}).(options.Names_ECM{iii,:})(tempValue,1)<0 ...
                    || battery_res.ECM.(options.Names_Elements{ii,:}).(options.Names_ECM{iii,:})(tempValue,1)==0 ...
                    || isnan(battery_res.ECM.(options.Names_Elements{ii,:}).(options.Names_ECM{iii,:})(tempValue,1))>0
                msg.error.ECM.Zarc=1;
                battery_res.ECM.(options.Names_Elements{ii,:}).(options.Names_ECM{iii,:})(tempValue,1)=battery_res.ECM.(options.Names_Elements{ii,:}).(options.Names_ECM{iii,:})(tempValue,1).*floor(1-battery_res.ECM.(options.Names_Elements{ii,:}).(options.Names_ECM{iii,:})(tempValue,1)./abs(battery_res.ECM.(options.Names_Elements{ii,:}).(options.Names_ECM{iii,:})(tempValue,1)*1.05)) ...
                    +floor(1-battery_res.ECM.(options.Names_Elements{ii,:}).(options.Names_ECM{iii,:})(tempValue,1)./abs(battery_res.ECM.(options.Names_Elements{ii,:}).(options.Names_ECM{iii,:})(tempValue,1)*1.05))*1e-3;
            end
        end
    end
    
    %WarBurg
    for ii=3:3
        for iii=1:6
            battery_res.ECM.(options.Names_Elements{ii,:}).(options.Names_ECM{iii,:})(tempValue,1)= ...
                interp1(param.fit.ECM.SoC,param.fit.ECM.(options.Names_Elements{ii,:}).(options.Names_ECM{iii,:}),battery_res.Cell.SoC(tempValue,1));
            if battery_res.ECM.(options.Names_Elements{ii,:}).(options.Names_ECM{iii,:})(tempValue,1)<0 ...
                    || battery_res.ECM.(options.Names_Elements{ii,:}).(options.Names_ECM{iii,:})(tempValue,1)==0 ...
                    || isnan(battery_res.ECM.(options.Names_Elements{ii,:}).(options.Names_ECM{iii,:})(tempValue,1))>0
                msg.error.ECM.WarBurg=1;
                battery_res.ECM.(options.Names_Elements{ii,:}).(options.Names_ECM{iii,:})(tempValue,1)=battery_res.ECM.(options.Names_Elements{ii,:}).(options.Names_ECM{iii,:})(tempValue,1).*floor(1-battery_res.ECM.(options.Names_Elements{ii,:}).(options.Names_ECM{iii,:})(tempValue,1)./abs(battery_res.ECM.(options.Names_Elements{ii,:}).(options.Names_ECM{iii,:})(tempValue,1)*1.05)) ...
                    +floor(1-battery_res.ECM.(options.Names_Elements{ii,:}).(options.Names_ECM{iii,:})(tempValue,1)./abs(battery_res.ECM.(options.Names_Elements{ii,:}).(options.Names_ECM{iii,:})(tempValue,1)*1.05))*1e-3;
            end
        end
    end
    
    %R0
    battery_res.ECM.R(tempValue,1)=interp1(param.fit.ECM.SoC,param.fit.ECM.R0,battery_res.Cell.SoC(tempValue,1));
    if battery_res.ECM.R(tempValue,1)<0 ...
            || battery_res.ECM.R(tempValue,1)==0 ...
            || isnan(battery_res.ECM.R(tempValue,1))>0
        msg.error.ECM.R=1;
        battery_res.ECM.R(tempValue,1)=battery_res.ECM.R(tempValue,1).*floor(battery_res.ECM.R(tempValue,1)./abs(battery_res.ECM.R(tempValue,1)*1.05)) ...
            +floor(1-battery_res.ECM.R(tempValue,1)./abs(rbattery_res.ECM.R(tempValue,1)*1.05))*1e-3;
    end
end
%Entropy ##################################################################
battery_res.Entropy(tempValue,1)=0;  %Add function
end

