function [calc_value, data_save] = structure_ECM_0D(options)

% Initilization ###########################################################
calc_value=struct(...
    'time',zeros(2,1) ...
        ,'P',zeros(2,1) ...
        ,'P_control',zeros(2,1) ...
        ,'I',zeros(2,1) ...
        ,'U',zeros(2,1) ...
        ,'T',zeros(2,1) ...
        ,'SoC',zeros(2,1) ...
        ,'OCV',zeros(2,1) ...
        ,'h',zeros(2,1) ...
        ,'Q',zeros(1,1) ...
        ,'Entropy',zeros(2,1) ...
        ,'Q_irr',zeros(1,1) ...
        ,'Q_rev',zeros(1,1) ...
        ,'Q_cooling',zeros(1,1) ...
    ,'ECM',struct(...
        'R',zeros(2,1) ...
        ,'R_RC1',zeros(2,1) ...
        ,'tau_RC1',zeros(2,1) ...
        ,'R_RC2',zeros(2,1) ...
        ,'tau_RC2',zeros(2,1) ...
        ,'R_RC3',zeros(2,1) ...
        ,'tau_RC3',zeros(2,1) ...
        ,'Usc',zeros(2,1) ...
        ,'U_R',zeros(2,1) ...
        ,'U_RC1',zeros(2,1) ...
        ,'U_RC2',zeros(2,1) ...
        ,'U_RC3',zeros(2,1) ...
        )...
      ,'Aging',struct(... 
         'SoH_C',zeros(1,1) ...
        ,'SoH_R',zeros(1,1) ...
        )...
     );
% Structure to Save Data ##################################################
data_save.time=zeros(1,1);
% All of this is just initializing all the saved information to zero so
% that the program allocates approperate amount of space.

% Cell, currently this is the only data being saved.
for trans=1:length(options.Save.Cell(:,1))
    data_save.(options.Save.Cell{trans,:})=zeros(1,1);
end
end

